### ISSUE TITLE
Foreground/Background clarification

### ISSUE THREAD

**Issue by LukasLauterbach** [ununhexium/cecho#4]
The spec states the following regarding foreground and background color specifiers:

> Split with slash foreground over background.
#foreground/background
**Either side is optional.**

I think the `either side is optional` part is not universally true (only for truecolor RRGGBB), because as far as I know, there is no way in 16 color mode to set only the background without explicitly setting the foreground. I also don't think there is a way to know for certain what the `regular` foreground color would be.

Did I overlook something or must this part of the spec more specific?

**Comment by LukasLauterbach** [comment]
Ah nevermind probably, I thought about it wrong.
In my head the foreground and background part were completely separate and could be at different positions.
According to the spec this is of course not true.
One can either specify a `#foreground` or a `#/background` or `#foreground/background`. Therefore in the case of `#/background`, the foreground will just be set to color '0' (black) because the foreground could not have been set to something else right?

**Comment by ununhexium** [comment]
In case of `#/background` it will only set a background color and keep the terminal's default color in the foreground.
Try `\x1b[1;42m` to only set the background to green. For instance in `echo 'default \e[1;42m BACK  \e[1;34m FORE'`.

And yes the default color in unknown. So better specify both to make it readable to bright and dark themes.

**Comment by LukasLauterbach** [comment]
Thanks for the clarification!
